### ISSUE TITLE
Update to hibernate search 5.9.x

### ISSUE THREAD

**Issue by olliefreeman** [mathpere/grails-hibernate-search-plugin#37]
Do you have plans/timeline to update to 5.9.x and incorporate Simple Query String queries using the Lucene SimpleQueryParser?

**Comment by lgrignon** [comment]
Hello @olliefreeman sorry but no, I wasn't planning to upgrade. Do you want to give it a try and PR?

**Comment by lgrignon** [comment]
@davebrown1975  The initial development of this plugin is done for a long time now, but as an open source project, it is maintained by the community. I myself contributed and upgraded to GORM 5, 6 & 6.1 but I won't have time for such a minor update. However, upgrading / contributing to this project is pretty easy, that's why I suggested olliefreeman to PR.

**Comment by davebrown1975** [comment]
Ok, thanks for clarifying.

**Comment by davebrown1975** [comment]
Hi again,  I have been able to use the simpleQueryString() using the current plugin,  in my project build configuration I've had to specify the following dependency versions, (my app is Grails v3.3.3)

compile "org.hibernate:hibernate-core:5.2.16.Final"
compile "org.hibernate:hibernate-ehcache:5.2.16.Final"
compile("org.hibernate:hibernate-search-orm:5.9.1.Final")
compile("org.grails.plugins:hibernate-search:2.2.0")

I wanted to help fork/update the plugin but noticed there's no test suite to execute, and I'd hate to break something

**Comment by lgrignon** [comment]
Should be solved with https://github.com/mathpere/grails-hibernate-search-plugin/pull/41 thanks to @olliefreeman
